#!/usr/bin/env python3
"""Write docs/status-archive/MOVE-MAP.md: where each part of the base status file went.

Usage: python3 tools/records/move-map.py --base <rev> [--repo .] [--root .]

Keyed by heading, row id or bullet, never by line number alone: one row per
heading, per work-package row, per closeout-blocker and residual row, and per
bullet of the deviation, evidence and gate sections. The archive file comes from
the split rules (status_sections.SECTIONS); the brief location is found by
searching the current brief for the id, so re-run this after editing the brief.
Stdlib only, no network.
"""

import argparse
import os
import re
import sys

sys.dont_write_bytecode = True  # keep tools/records free of __pycache__
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
import status_sections as S  # noqa: E402

BULLET_SECTIONS = ["## Accepted evidence", "## Deviations from specification", "## Pending external evidence",
                   "## Resolved evidence items", "## Human and operational gates"]

# Base heading prefix -> the brief section that now carries its live content.
HEADING_TO_BRIEF = [
    ("# Implementation Status", "title block; Current phase"),
    ("## Safety state", "Safety state (verbatim)"),
    ("## Work packages", "Work packages (one line per package); Authorized now"),
    ("## Accepted evidence", "Resolved evidence items (one line)"),
    ("## Wave 2 qualification", "Wave 2 qualification (one paragraph)"),
    ("### Superseded header sentences", "archive only"),
    ("## Open blockers", "Open blockers"),
    ("### Closeout blockers still open", "Open blockers > Closeout blockers"),
    ("### Residual queue", "Open blockers > Residual queue"),
    ("### The cross-package record below, reconciled", "Open blockers > Schema boundary (still live)"),
    ("### Cross-package risk", "Open blockers > Schema boundary (still live); archive"),
    ("## Deviations from specification", "Deviations from specification (one line each)"),
    ("## Pending external evidence", "Pending external evidence"),
    ("## Resolved evidence items", "Resolved evidence items"),
    ("## Human and operational gates", "Human and operational gates (verbatim)"),
]


def brief_index(brief_lines):
    """For each line, the heading path (## and ###) it sits under."""
    h2 = h3 = ""
    out = []
    for line in brief_lines:
        if line.startswith("## "):
            h2, h3 = line[3:], ""
        elif line.startswith("### "):
            h3 = line[4:]
        out.append(f"{h2} > {h3}" if h3 else h2)
    return out


def locate(ident, brief_lines, where, prefer=None):
    """The brief location of an id: its own table row, else its first mention.

    prefer is a sequence of heading-path prefixes, searched in order before the whole brief.
    """
    for scope in prefer or ():
        scoped = [l if where[i].startswith(scope) else "" for i, l in enumerate(brief_lines)]
        found = locate(ident, scoped, where)
        if found != "archive only":
            return found
    tick = f"`{ident}`"
    row = [i for i, l in enumerate(brief_lines) if l.startswith(f"| {tick} |")]
    if row:
        return f"{where[row[0]]} (own row)"
    hits = [i for i, l in enumerate(brief_lines) if tick in l or f"**{ident}**" in l]
    if hits:
        return f"{where[hits[0]]} (named)"
    heads = [i for i, l in enumerate(brief_lines) if l.startswith("#") and ident in l]
    if heads:
        return f"{where[heads[0]]} (section)"
    return "archive only"


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    ap.add_argument("--base", required=True)
    ap.add_argument("--repo", default=".")
    ap.add_argument("--root", default=None)
    args = ap.parse_args()
    root = args.root or args.repo
    sha = S.resolve(args.repo, args.base)
    lines = S.base_text(args.repo, sha).split("\n")
    starts = S.section_starts(S.split_lines(S.base_text(args.repo, sha)))

    def archive_of(n):  # 1-based line -> archive file
        k = max(i for i, s in enumerate(starts) if s + 1 <= n)
        return S.SECTIONS[k][0]

    with open(os.path.join(root, S.STATUS), encoding="utf-8") as fh:
        brief = fh.read().split("\n")
    where = brief_index(brief)

    out = [
        "# Status archive: move map",
        "",
        f"Where each part of `IMPLEMENTATION_STATUS.md` at `{sha[:7]}` went. Generated by",
        "`tools/records/move-map.py`; the brief column is found by searching the brief",
        "for the id. Line numbers are for orientation only; key on the id or heading.",
        "",
        "To re-apply a governance edit made on `main` after the cut: find its id below,",
        "update that one line in the brief, and re-cut the archive (see `README.md`).",
        "",
        "## Headings",
        "",
        "| Old heading | Old line | Archive file | Brief section |",
        "| --- | --- | --- | --- |",
    ]
    for n, line in enumerate(lines, 1):
        if re.match(r"^#{1,6} ", line):
            dest = next((b for p, b in HEADING_TO_BRIEF if line.startswith(p)), "archive only")
            out.append(f"| {line} | {n} | [{archive_of(n)}]({archive_of(n)}) | {dest} |")

    out += ["", "## Work-package rows", "", "| Row id | Old line | Archive file | Brief location |", "| --- | --- | --- | --- |"]
    on = False
    for n, line in enumerate(lines, 1):
        if line == "## Work packages":
            on = True
            continue
        if on and line.startswith("#"):
            break
        m = re.match(r"^\| ((?:\(superseded row\) )?)`([A-Za-z0-9-]+)`", line) if on else None
        if m:
            label = f"{m.group(1)}`{m.group(2)}`"
            dest = locate(m.group(2), brief, where, prefer=("Work packages",))
            if locate(m.group(2), brief, where, prefer=("Authorized now",)).startswith("Authorized now"):
                dest += "; Authorized now"
            out.append(f"| {label} | {n} | [{archive_of(n)}]({archive_of(n)}) | {dest} |")
        elif on and line.startswith("| All other packages"):
            out.append(f"| All other packages | {n} | [{archive_of(n)}]({archive_of(n)}) | Work packages (own row) |")

    out += ["", "## Closeout-blocker and residual rows", "",
            "| Row id (as in the old table) | Old line | Archive file | Brief location |", "| --- | --- | --- | --- |"]
    on = False
    sub = ""
    for n, line in enumerate(lines, 1):
        if line == "## Open blockers":
            on = True
            continue
        if on and line.startswith("### "):
            sub = line
        if on and (line.startswith("## ") or line.startswith("### The cross-package")):
            break
        m = re.match(r"^\| \*\*(.+?)\*\* \|", line) if on else None
        if m:
            raw = m.group(1).replace("**", "")
            ident = re.sub(r" \(.*\)$", "", raw).strip()
            label = f"`{ident}`" + ("" if raw == ident else " (" + raw.replace("|", "\\|") + ")")
            first = "Open blockers > Closeout" if sub.startswith("### Closeout") else "Open blockers > Residual queue"
            dest = locate(ident, brief, where, prefer=(first, "Open blockers", "Human items"))
            out.append(f"| {label} | {n} | [{archive_of(n)}]({archive_of(n)}) | {dest} |")

    out += ["", "## Bullets of the deviation, evidence and gate sections", "",
            "| Old section | Bullet (first words) | Old line | Archive file | Brief section |", "| --- | --- | --- | --- | --- |"]
    cur = None
    for n, line in enumerate(lines, 1):
        if line.startswith("#"):
            cur = line if line in BULLET_SECTIONS else None
            continue
        if cur and line.startswith("- "):
            words = " ".join(line[2:].split()[:9]).replace("|", "\\|")
            dest = next(b for p, b in HEADING_TO_BRIEF if cur.startswith(p))
            out.append(f"| {cur[3:]} | {words} ... | {n} | [{archive_of(n)}]({archive_of(n)}) | {dest} |")
    out.append("")
    path = os.path.join(root, S.ARCHIVE, "MOVE-MAP.md")
    with open(path, "w", encoding="utf-8") as fh:
        fh.write("\n".join(out))
    print(f"wrote {path}: {len(out)} lines")
    return 0


if __name__ == "__main__":
    sys.exit(main())
