#!/usr/bin/env python3
"""Split a base IMPLEMENTATION_STATUS.md into docs/status-archive/*.md, verbatim.

Usage: python3 tools/records/split-status.py --base <rev> [--repo .] [--out docs/status-archive]

Each archive file holds ONE contiguous region of the base file, byte for byte,
between verbatim markers that carry the base commit, the line range and the
region's sha256. Together the regions partition the base file. Deterministic,
stdlib only, no network. It overwrites only the SECTIONS files it owns.
"""

import argparse
import os
import sys

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
import status_sections as S  # noqa: E402


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    ap.add_argument("--base", required=True, help="the commit whose IMPLEMENTATION_STATUS.md is archived")
    ap.add_argument("--repo", default=".")
    ap.add_argument("--out", default=None, help="default: <repo>/docs/status-archive")
    args = ap.parse_args()

    sha = S.resolve(args.repo, args.base)
    text = S.base_text(args.repo, sha)
    lines = S.split_lines(text)
    starts = S.section_starts(lines)
    out = args.out or os.path.join(args.repo, S.ARCHIVE)
    os.makedirs(out, exist_ok=True)

    joined = []
    for k, (name, title, _kind, _rule, desc) in enumerate(S.SECTIONS):
        a = starts[k]
        b = starts[k + 1] if k + 1 < len(starts) else len(lines)
        region = "".join(lines[a:b])
        joined.append(region)
        if not region.endswith("\n"):
            region += "\n"  # only possible for a base file without a final newline
        body = (
            f"# Status archive: {title}\n\n"
            f"Verbatim lines {a + 1}-{b} of `{S.STATUS}` at `{sha[:7]}`: {desc}; "
            f"generated by `tools/records/split-status.py`, do not edit.\n\n"
            f"<!-- verbatim-begin source={S.STATUS} base={sha} lines={a + 1}-{b} "
            f"sha256={S.sha256(''.join(lines[a:b]).encode('utf-8'))} -->\n"
            f"{region}{S.END_LINE}\n"
        )
        with open(os.path.join(out, name), "w", encoding="utf-8", newline="") as fh:
            fh.write(body)
        print(f"{name}: lines {a + 1}-{b} ({len(''.join(lines[a:b]).encode('utf-8'))} B)")

    assert "".join(joined) == text, "regions do not reproduce the base file"
    print(f"base {sha}: {len(lines)} lines, {len(text.encode('utf-8'))} B, sha256 {S.sha256(text.encode('utf-8'))}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
