/**
 * Starts one throwaway PostgreSQL container for the whole integration run and
 * publishes its admin connection URL to the test files.
 *
 * One container, many databases: starting a container per file would multiply
 * the run time by the file count for no isolation gain, because a fresh
 * database inside one server is already fully isolated for these tests.
 *
 * The credentials are generated by Testcontainers and live only as long as the
 * container. No real credential is read or required (§0.2, ADR-010).
 */

import { startPostgresContainer } from "@polymarket-bot/storage-postgres/testing";
import type { TestProject } from "vitest/node";

declare module "vitest" {
  export interface ProvidedContext {
    postgresAdminUrl: string;
  }
}

export default async function setup(project: TestProject): Promise<() => Promise<void>> {
  const container = await startPostgresContainer();
  project.provide("postgresAdminUrl", container.getConnectionUri());

  return async () => {
    await container.stop();
  };
}
