/**
 * `ROLLOVER-1` test samples: a reviewed `btc-15m-updown` series and one window
 * as the admission judge reads it.
 *
 * UNLIKE `./index.ts`, these values are RECORDED venue data, quoted from
 * `docs/venue/verified-2026-10-04.md` (VENUE-SETL-1) and its saved bodies:
 *
 * - the series: Gamma series `10192`, slug `btc-up-or-down-15m` (F-10, S-G01);
 * - the window: event `1127115`, market `5255913`, "Bitcoin Up or Down -
 *   October 4, 6:15PM-6:30PM ET", 2026-10-04T22:15Z..22:30Z, condition
 *   `0x5e196ca7…`, tokens Up/Down in that order (S-G03, the first event of
 *   `GET /events/keyset?series_id=10192&closed=false&…`, fetched 22:31:12Z,
 *   sha256 `17596e63…`), tick 0.001;
 * - its CLOB market info (S-K03a, `GET /clob-markets/0x5e196ca7…`, sha256
 *   `92de0d99…`): the same token order, `mos` 5, `mts` 0.001, `mbf`/`tbf` 1000,
 *   `itode` true, `fd {r 0.07, e 1, to true}`;
 * - the rules text, verbatim (F-22; sha256 `485ceb1d…`).
 *
 * The REVIEW itself (`review`, `settlement`, `trading`, the cap) is sample
 * configuration, not a venue fact: no human has reviewed this series' settlement
 * (`CLOSEOUT-2` N2), which is why `modelDependentActivationAllowed` is `false`.
 */

import type {
  ClobMarketInfoReading,
  GammaWindowEventReading,
  GammaWindowMarketReading,
} from "../series-admission.js";

/** The rules text of every TWAP-rule window, verbatim (F-22). */
export const BTC_15M_RULES_TEXT =
  'This market will resolve to "Up" if the time-weighted average price (TWAP) of Bitcoin, generated by Chainlink, of the time range specified in the title is greater than or equal to the price at the beginning of that range. Otherwise, it will resolve to "Down".\n' +
  "The resolution source for this market is information from Chainlink, specifically the BTC/USD TWAP data stream available at https://data.chain.link/streams/btc-usd-twap-60s-streams.\n" +
  "Please note that this market is about the price according to the TWAP Chainlink data stream for the asset pair BTC/USD, not according to any other sources or spot markets.";

export const BTC_15M_RULES_SHA256 = "485ceb1dabc4aa12fb42c76184563b7378f01e5de9ded73df049c0d191cd5ad1";

export const RECORDED_WINDOW = Object.freeze({
  eventId: "1127115",
  marketId: "5255913",
  title: "Bitcoin Up or Down - October 4, 6:15PM-6:30PM ET",
  conditionId: "0x5e196ca7c84c54fb1482ca206df477bba1fb3d8c813580c3838186cedde32b29",
  yesTokenId: "82133233861314798028087473521332912369939570267929634486524845895982963276831",
  noTokenId: "77032538501070316350656311299825606177844598103814694895686056289307323150761",
  eventStartTime: "2026-10-04T22:15:00Z",
  endDate: "2026-10-04T22:30:00Z",
  openAt: "2026-10-04T22:15:00.000Z",
  closeAt: "2026-10-04T22:30:00.000Z",
  tickSize: "0.001",
});

/** A reviewed `btc-15m-updown` series document, as configuration states it. */
export function reviewedBtc15mSeriesDocument(): Record<string, unknown> {
  return {
    seriesId: "btc-15m-updown",
    review: {
      reviewedBy: "sample-reviewer",
      reviewedAt: "2026-10-04T23:00:00Z",
      reference: "docs/venue/verified-2026-10-04.md",
    },
    venue: { gammaSeriesId: "10192", seriesSlug: "btc-up-or-down-15m" },
    window: {
      titlePrefix: "Bitcoin Up or Down - ",
      titleTimeZone: "America/New_York",
      titleZoneLabel: "ET",
      durationSeconds: 900,
    },
    rules: {
      descriptionSha256: BTC_15M_RULES_SHA256,
      resolutionSource: "https://data.chain.link/streams/btc-usd-twap-60s-streams",
    },
    outcomes: ["Up", "Down"],
    parameters: {
      allowedTickSizes: ["0.01", "0.001"],
      minimumOrderSize: "5",
      negRisk: false,
      fees: {
        feesEnabled: true,
        rate: "0.07",
        exponent: "1",
        takerOnly: true,
        rebateRate: "0.2",
        makerBaseFee: "1000",
        takerBaseFee: "1000",
      },
      tradingDelay: { takerOrderDelayEnabled: true, gammaSecondsDelay: "NOT_STATED" },
      catalogTradingDelaySeconds: 0,
    },
    settlement: { specRef: "btc-15m-updown", modelDependentActivationAllowed: false },
    trading: {
      makerFeeRate: "0",
      takerFeeRate: "0",
      seriesKey: "btc-15m-updown",
      underlyingKey: "btc.usd",
      resolutionWindowKey: "btc-15m-window",
    },
    maximumConcurrentWindows: 2,
    unresolvedTeardownSeconds: 3600,
  };
}

/** The recorded window's market, as the door reads it (S-G03). */
export function recordedWindowMarketReading(
  overrides: Partial<GammaWindowMarketReading> = {},
): GammaWindowMarketReading {
  return {
    marketId: RECORDED_WINDOW.marketId,
    question: RECORDED_WINDOW.title,
    conditionId: RECORDED_WINDOW.conditionId,
    description: BTC_15M_RULES_TEXT,
    resolutionSource: "https://data.chain.link/streams/btc-usd-twap-60s-streams",
    outcomes: '["Up", "Down"]',
    clobTokenIds: JSON.stringify([RECORDED_WINDOW.yesTokenId, RECORDED_WINDOW.noTokenId]),
    eventStartTime: RECORDED_WINDOW.eventStartTime,
    endDate: RECORDED_WINDOW.endDate,
    orderPriceMinTickSize: { kind: "VALUE", value: RECORDED_WINDOW.tickSize },
    orderMinSize: { kind: "VALUE", value: "5" },
    secondsDelay: { kind: "ABSENT" },
    feesEnabled: true,
    feeSchedule: {
      rate: { kind: "VALUE", value: "0.07" },
      exponent: { kind: "VALUE", value: "1" },
      takerOnly: true,
      rebateRate: { kind: "VALUE", value: "0.2" },
    },
    makerBaseFee: { kind: "VALUE", value: "1000" },
    takerBaseFee: { kind: "VALUE", value: "1000" },
    ...overrides,
  };
}

/** The recorded window's event, as the door reads it (S-G03). */
export function recordedWindowEventReading(
  overrides: Partial<GammaWindowEventReading> = {},
  market: Partial<GammaWindowMarketReading> = {},
): GammaWindowEventReading {
  return {
    eventId: RECORDED_WINDOW.eventId,
    eventTitle: RECORDED_WINDOW.title,
    eventSeriesSlug: "btc-up-or-down-15m",
    eventSeriesIds: ["10192"],
    eventNegRisk: false,
    marketCount: 1,
    market: recordedWindowMarketReading(market),
    ...overrides,
  };
}

/** The recorded window's CLOB market info, as the door reads it (S-K03a). */
export function recordedClobReading(overrides: Partial<ClobMarketInfoReading> = {}): ClobMarketInfoReading {
  return {
    tokens: [
      { tokenId: RECORDED_WINDOW.yesTokenId, outcome: "Up" },
      { tokenId: RECORDED_WINDOW.noTokenId, outcome: "Down" },
    ],
    minimumOrderSize: { kind: "VALUE", value: "5" },
    minimumTickSize: { kind: "VALUE", value: RECORDED_WINDOW.tickSize },
    makerBaseFee: { kind: "VALUE", value: "1000" },
    takerBaseFee: { kind: "VALUE", value: "1000" },
    takerOrderDelayEnabled: true,
    fees: {
      rate: { kind: "VALUE", value: "0.07" },
      exponent: { kind: "VALUE", value: "1" },
      takerOnly: true,
    },
    ...overrides,
  };
}
