/**
 * One throwaway PostgreSQL container for this runner (Testcontainers,
 * `packages/storage-postgres`'s own image pin), its admin URL published to the
 * test files. The credentials are generated by Testcontainers and live only as
 * long as the container; no real credential is read or required. The container
 * is stopped (and Testcontainers' reaper removes it) when the run ends.
 */

import type { TestProject } from "vitest/node";

import { startPostgresContainer } from "../../../../packages/storage-postgres/src/testing/index.js";

declare module "vitest" {
  export interface ProvidedContext {
    wp340PostgresAdminUrl: string;
  }
}

export default async function setup(project: TestProject): Promise<() => Promise<void>> {
  const container = await startPostgresContainer();
  project.provide("wp340PostgresAdminUrl", container.getConnectionUri());
  return async () => {
    await container.stop();
  };
}
