/**
 * Starts one throwaway Redis container for the whole integration run and
 * publishes its connection URL to the test files.
 *
 * One container, many streams: starting a container per file would multiply the
 * run time by the file count for no isolation gain, because a uniquely named
 * stream inside one server is already fully isolated for these tests.
 *
 * The port is generated by Testcontainers and the container lives only as long
 * as the run. No real credential is read or required (§0.2, ADR-010).
 */

import { startRedisContainer } from "@polymarket-bot/event-bus/testing";
import type { TestProject } from "vitest/node";

declare module "vitest" {
  export interface ProvidedContext {
    redisUrl: string;
  }
}

export default async function setup(project: TestProject): Promise<() => Promise<void>> {
  const container = await startRedisContainer();
  project.provide("redisUrl", container.getConnectionUrl());

  return async () => {
    await container.stop();
  };
}
